[package]
name = "solve2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]
# crate-type = ["cdylib"]

[dependencies]
const_for = "0.1.4"
lazy_static = "1.4.0"
rand = "0.8.5"
wasm-bindgen = "0.2.92"
rayon = "1"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "monte_carlo"
harness = false
